version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: listen
    versions:
    - ">= 3.2.a"
    - "< 3.3"
