version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "05:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "05:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "05:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
