version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3
  node: circleci/node@4.7.0
  ruby: circleci/ruby@1.2.0

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.0.3-browsers
        environment:
          RAILS_ENV: test

commands:
  install_node:
    steps:
      - node/install:
          lts: true
          install-yarn: true
  set_up_database:
    steps:
      - run:
          name: Set Up Database
          command: bundle exec rake db:setup

jobs:
  test:
    executor: ruby
    steps:
      - install_node
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - set_up_database
      - run:
          name: Run Tests
          command: bundle exec rake test
  test_system:
    executor: ruby
    steps:
      - browser-tools/install-chrome
      - install_node
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - set_up_database
      - run:
          name: Run System Tests
          command: |
            bundle exec rake webdrivers:chromedriver:update
            bundle exec rake test:system
      - store_artifacts:
          path: ./tmp/screenshots
          destination: screenshots

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
      - test_system
  cron-workflow:
    jobs:
      - test
      - test_system
    triggers:
      - schedule:
          cron: "0 13 * * 6"
          filters:
            branches:
              only:
                - main
